/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dethitracnghiem.client;

/**
 *
 * @author USER
 */
public class formAdminHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form formAdminHomeScreen
     */
    public formAdminHomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTaoBoCauHoi = new javax.swing.JButton();
        btnDanhSachDeThi = new javax.swing.JButton();
        btnCapNhatCauHoi = new javax.swing.JButton();
        btnXoaCauHoi = new javax.swing.JButton();
        btnThongTinThiSinh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTaoBoCauHoi.setBackground(new java.awt.Color(0, 153, 0));
        btnTaoBoCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnTaoBoCauHoi.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoBoCauHoi.setText("Tạo bộ câu hỏi");
        btnTaoBoCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoBoCauHoiActionPerformed(evt);
            }
        });

        btnDanhSachDeThi.setBackground(new java.awt.Color(0, 102, 204));
        btnDanhSachDeThi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDanhSachDeThi.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSachDeThi.setText("Danh sách đề thi");
        btnDanhSachDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachDeThiActionPerformed(evt);
            }
        });

        btnCapNhatCauHoi.setBackground(new java.awt.Color(153, 153, 0));
        btnCapNhatCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCapNhatCauHoi.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatCauHoi.setText("Cập nhật câu hỏi");
        btnCapNhatCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatCauHoiActionPerformed(evt);
            }
        });

        btnXoaCauHoi.setBackground(new java.awt.Color(153, 0, 0));
        btnXoaCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnXoaCauHoi.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaCauHoi.setText("Xóa câu hỏi");
        btnXoaCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCauHoiActionPerformed(evt);
            }
        });

        btnThongTinThiSinh.setBackground(new java.awt.Color(0, 102, 102));
        btnThongTinThiSinh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnThongTinThiSinh.setForeground(new java.awt.Color(255, 255, 255));
        btnThongTinThiSinh.setText("Thông tin cá nhân");
        btnThongTinThiSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinThiSinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThongTinThiSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTaoBoCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCapNhatCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDanhSachDeThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaCauHoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoBoCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhatCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDanhSachDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnThongTinThiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoBoCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoBoCauHoiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new formTaoDeThi().setVisible(true);
    }//GEN-LAST:event_btnTaoBoCauHoiActionPerformed

    private void btnCapNhatCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatCauHoiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new formCapNhatCauHoi().setVisible(true);
    }//GEN-LAST:event_btnCapNhatCauHoiActionPerformed

    private void btnDanhSachDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachDeThiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new formDanhSachDeThi().setVisible(true);
    }//GEN-LAST:event_btnDanhSachDeThiActionPerformed

    private void btnXoaCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCauHoiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new formXoaCauHoi().setVisible(true);
    }//GEN-LAST:event_btnXoaCauHoiActionPerformed

    private void btnThongTinThiSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinThiSinhActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new formAdminStudent().setVisible(true);
    }//GEN-LAST:event_btnThongTinThiSinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAdminHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formAdminHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatCauHoi;
    private javax.swing.JButton btnDanhSachDeThi;
    private javax.swing.JButton btnTaoBoCauHoi;
    private javax.swing.JButton btnThongTinThiSinh;
    private javax.swing.JButton btnXoaCauHoi;
    // End of variables declaration//GEN-END:variables
}
