/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dethitracnghiem.client;

import dethitracnghiem.server.CauHoi;
import dethitracnghiem.server.DeThi;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */

public class formTaoDeThi extends javax.swing.JFrame {
    private DeThi deThi = null;
    private ArrayList<CauHoi> cauHoiList = new ArrayList<>();
    /**
     * Creates new form formTaoDeThi
     */
    public formTaoDeThi() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupChonDapAn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtC = new javax.swing.JTextField();
        txtD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtnA = new javax.swing.JRadioButton();
        rbtnB = new javax.swing.JRadioButton();
        rbtnC = new javax.swing.JRadioButton();
        rbtnD = new javax.swing.JRadioButton();
        btnCauTiepTheo = new javax.swing.JButton();
        btnLuuDSCauHoi = new javax.swing.JButton();
        jlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMonThi = new javax.swing.JTextField();
        btnSetDeThi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        lblCauHoiSo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TẠO BỘ CÂU HỎI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(379, 379, 379))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setText("Nội dung:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel3.setText("Đáp án:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel4.setText("A");

        txtA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel5.setText("B");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel6.setText("C");

        txtC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel8.setText("D");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel9.setText("Đáp án đúng:");

        groupChonDapAn.add(rbtnA);
        rbtnA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtnA.setText("A");

        groupChonDapAn.add(rbtnB);
        rbtnB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtnB.setText("B");

        groupChonDapAn.add(rbtnC);
        rbtnC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtnC.setText("C");

        groupChonDapAn.add(rbtnD);
        rbtnD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtnD.setText("D");

        btnCauTiepTheo.setBackground(new java.awt.Color(204, 102, 0));
        btnCauTiepTheo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCauTiepTheo.setForeground(new java.awt.Color(255, 255, 255));
        btnCauTiepTheo.setText("Câu tiếp theo");
        btnCauTiepTheo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCauTiepTheoActionPerformed(evt);
            }
        });

        btnLuuDSCauHoi.setBackground(new java.awt.Color(0, 102, 0));
        btnLuuDSCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLuuDSCauHoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuDSCauHoi.setText("Lưu danh sách câu hỏi");
        btnLuuDSCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuDSCauHoiActionPerformed(evt);
            }
        });

        jlabel.setBackground(new java.awt.Color(0, 0, 0));
        jlabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jlabel.setText("Câu hỏi số:");

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Môn thi:");

        txtMonThi.setBackground(new java.awt.Color(255, 255, 255));
        txtMonThi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnSetDeThi.setBackground(new java.awt.Color(153, 0, 255));
        btnSetDeThi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSetDeThi.setForeground(new java.awt.Color(255, 255, 255));
        btnSetDeThi.setText("OK");
        btnSetDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDeThiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addComponent(btnSetDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMonThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSetDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtNoiDung.setColumns(20);
        txtNoiDung.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNoiDung.setRows(5);
        jScrollPane1.setViewportView(txtNoiDung);

        lblCauHoiSo.setBackground(new java.awt.Color(0, 0, 0));
        lblCauHoiSo.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblCauHoiSo.setForeground(new java.awt.Color(255, 0, 0));
        lblCauHoiSo.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtD))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCauTiepTheo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuuDSCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(40, 40, 40)
                                .addComponent(rbtnA)
                                .addGap(54, 54, 54)
                                .addComponent(rbtnB)
                                .addGap(63, 63, 63)
                                .addComponent(rbtnC)
                                .addGap(67, 67, 67)
                                .addComponent(rbtnD))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlabel)
                                .addGap(18, 18, 18)
                                .addComponent(lblCauHoiSo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtB)
                            .addComponent(txtA)
                            .addComponent(txtC))))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel)
                    .addComponent(lblCauHoiSo))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30)
                                .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rbtnA)
                    .addComponent(rbtnB)
                    .addComponent(rbtnC)
                    .addComponent(rbtnD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuuDSCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCauTiepTheo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean validateFields() {
        if(deThi == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập môn thi", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        String noiDung = this.txtNoiDung.getText();
        String A = this.txtA.getText();
        String B = this.txtB.getText();
        String C = this.txtC.getText();
        String D = this.txtD.getText();
        String chonDapAn = null;
        
        if(rbtnA.isSelected()) {
            chonDapAn = "A";
        } else if(rbtnB.isSelected()) {
            chonDapAn = "B";
        } else if(rbtnC.isSelected()) {
            chonDapAn = "C";
        } else if(rbtnD.isSelected()) {
            chonDapAn = "D";
        }
        
        if(noiDung.trim().isEmpty() || A.trim().isEmpty() || B.trim().isEmpty() || C.trim().isEmpty() || D.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập nội dung câu hỏi và 4 đáp án", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            if(chonDapAn == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn đáp án đúng!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return false;
            } else {
                return true;
            }
        }
    }
    
    private void btnCauTiepTheoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCauTiepTheoActionPerformed
        // TODO add your handling code here:
        themCauHoi();
    }//GEN-LAST:event_btnCauTiepTheoActionPerformed
        
    private void btnSetDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDeThiActionPerformed
        // TODO add your handling code here:
        String monThi = txtMonThi.getText();
        
        if(monThi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập môn thi!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Tạo đề thi đã thành công!");
            txtMonThi.setEditable(false);
            this.deThi = new DeThi(monThi);
        }
    }//GEN-LAST:event_btnSetDeThiActionPerformed
    
    private boolean themCauHoi() {
        boolean valid = validateFields();
        CauHoi cauHoi = new CauHoi();
        int cauHoiSo = 1;
        
        if(valid) {
            cauHoi.setA(txtA.getText().trim());
            cauHoi.setB(txtB.getText().trim());
            cauHoi.setC(txtC.getText().trim());
            cauHoi.setD(txtD.getText().trim());
            
                
            String dapAn = null;
            
            if(rbtnA.isSelected()) {
                dapAn = "A";
            } else if(rbtnB.isSelected()) {
                dapAn = "B";
            } else if(rbtnC.isSelected()) {
                dapAn = "C";
            } else if(rbtnD.isSelected()) {
                dapAn = "D";
            } 
            
            cauHoi.setDapAn(dapAn);
            cauHoi.setNoiDung(this.txtNoiDung.getText().trim());
            
            this.txtNoiDung.setText("");
            txtA.setText("");
            txtB.setText("");
            txtC.setText("");
            txtD.setText("");
            groupChonDapAn.clearSelection();
            
            cauHoiList.add(cauHoi);
            
            cauHoi.setDeThi(deThi);
            
            cauHoiSo++;
            lblCauHoiSo.setText(String.valueOf(cauHoiSo));
        } else {
            lblCauHoiSo.setText("1");
        }
        
        return valid;
    }
    
    private void btnLuuDSCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuDSCauHoiActionPerformed
        // TODO add your handling code here:
        boolean flag = themCauHoi();
        
        if(flag) {
            flag = deThi.save(cauHoiList);
            
            if(flag) {
                JOptionPane.showMessageDialog(this, "Lưu danh sách câu hỏi đã thành công");
                this.dispose();
                new formAdminHomeScreen().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Không lưu được danh sách câu hỏi! Vui lòng kiểm tra lại");
            }
        }
        
    }//GEN-LAST:event_btnLuuDSCauHoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTaoDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTaoDeThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCauTiepTheo;
    private javax.swing.JButton btnLuuDSCauHoi;
    private javax.swing.JButton btnSetDeThi;
    private javax.swing.ButtonGroup groupChonDapAn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lblCauHoiSo;
    private javax.swing.JRadioButton rbtnA;
    private javax.swing.JRadioButton rbtnB;
    private javax.swing.JRadioButton rbtnC;
    private javax.swing.JRadioButton rbtnD;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtMonThi;
    private javax.swing.JTextArea txtNoiDung;
    // End of variables declaration//GEN-END:variables

    
}